// Rebuilds: src/lib/zg/bundle.js + markup.js (used by the Next app)
// and ../index.html (standalone monolith, no backend needed).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('.', import.meta.url).pathname;
const M = join(ROOT, 'src/lib/zg/modules');
const read = f => readFileSync(join(M, f), 'utf8');

const css = read('styles.css');
const markup = read('markup.html');
const jsFiles = readdirSync(M).filter(f => f.endsWith('.js')).sort();
const js = jsFiles.map(f => '/* ---- ' + f + ' ---- */\n' + read(f)).join('\n\n');

writeFileSync(join(ROOT, 'src/lib/zg/bundle.js'),
  '/* GENERATED by build.mjs from src/lib/zg/modules/* — edit the modules, then rerun. */\n\'use strict\';\n' + js + '\n');
writeFileSync(join(ROOT, 'src/lib/zg/markup.js'), 'export const ZG_MARKUP = ' + JSON.stringify(markup) + ';\n');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ZipToGit Pro — GitHub Dashboard</title>
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'unsafe-inline'; img-src 'self' data: https://*.githubusercontent.com https://avatars.githubusercontent.com; connect-src 'self' https://api.github.com; font-src 'self' data: https://cdnjs.cloudflare.com; worker-src 'self' blob: https://cdnjs.cloudflare.com; base-uri 'none'; form-action 'none'">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop offset='0' stop-color='%235f6cf0'/%3E%3Cstop offset='1' stop-color='%234ea8de'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect x='4' y='4' width='56' height='56' rx='16' fill='url(%23g)'/%3E%3Cpath d='M22 20h20M22 32h20M22 44h12' stroke='white' stroke-width='5' stroke-linecap='round'/%3E%3C/svg%3E">
<style>
${css}
</style>
</head>
<body>
${markup}
<script>
'use strict';
${js}
</script>
</body>
</html>
`;
writeFileSync(join(ROOT, '..', 'index.html'), html);
console.log('✓ bundle.js + markup.js + ../index.html', (html.length / 1024).toFixed(0), 'KB');
